version: '3.4'

services:
  patientandencounterapidesign:
    image: patientandencounterapidesign
    build:
      context: server
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
